# Generated by Django 4.0.1 on 2022-01-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car1', models.CharField(default='', max_length=50)),
                ('Image1', models.ImageField(upload_to='images/')),
                ('Brand', models.CharField(default='', max_length=10)),
                ('Details', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=15)),
                ('Age', models.IntegerField(default='')),
                ('Place', models.CharField(default='', max_length=15)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Password', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
