# Generated by Django 4.0.1 on 2022-01-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='Car1',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='pictures',
            old_name='Image1',
            new_name='Image',
        ),
        migrations.AlterField(
            model_name='pictures',
            name='Brand',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='Details',
            field=models.CharField(default='', max_length=50),
        ),
    ]
